import React from 'react';
import { Appointment } from '../types';
import { Calendar, Clock, MapPin, User, Download, X } from 'lucide-react';
import { jsPDF } from "jspdf";

interface Props {
  appointment: Appointment;
  onClose: () => void;
}

export const AppointmentSlip: React.FC<Props> = ({ appointment, onClose }) => {
  
  const handleDownload = () => {
    try {
      // Ensure jsPDF is initialized correctly
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      
      // Header Background
      doc.setFillColor(37, 99, 235); // Blue-600
      doc.rect(0, 0, pageWidth, 40, 'F');
      
      // Header Text
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.setFont("helvetica", "bold");
      doc.text("MediAI Pro Hospital", pageWidth / 2, 20, { align: "center" });
      
      doc.setFontSize(12);
      doc.setFont("helvetica", "normal");
      doc.text("Official Appointment Slip", pageWidth / 2, 30, { align: "center" });

      // Content
      let y = 60;
      const leftMargin = 20;
      
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text("APPOINTMENT ID", leftMargin, y);
      doc.setFontSize(16);
      doc.setTextColor(0, 0, 0);
      doc.setFont("helvetica", "bold");
      doc.text(`#${appointment.id}`, leftMargin, y + 8);
      
      y += 25;
      
      // Patient Info
      doc.setDrawColor(200, 200, 200);
      doc.line(leftMargin, y, pageWidth - leftMargin, y);
      y += 15;

      doc.setFontSize(14);
      doc.text(`Patient: ${appointment.patientName}`, leftMargin, y);
      y += 8;
      doc.setFontSize(11);
      doc.setTextColor(80, 80, 80);
      doc.text(`Contact: ${appointment.phone}`, leftMargin, y);
      y += 15;

      // Doctor Info
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 0);
      doc.text(`Doctor: ${appointment.doctor.name}`, leftMargin, y);
      y += 8;
      doc.setFontSize(11);
      doc.setTextColor(37, 99, 235); // Blue
      doc.text(appointment.doctor.specialty, leftMargin, y);
      y += 15;

      // Timing
      doc.setTextColor(0, 0, 0);
      doc.text(`Date: ${appointment.date}`, leftMargin, y);
      doc.text(`Time: ${appointment.time}`, leftMargin + 80, y);
      y += 15;
      
      doc.text(`Location: ${appointment.doctor.location}`, leftMargin, y);

      // Footer
      y = 270;
      doc.setFontSize(10);
      doc.setTextColor(150, 150, 150);
      doc.text("Please arrive 15 minutes prior to your appointment.", pageWidth / 2, y, { align: "center" });
      doc.text("Generated by MediAI Pro System", pageWidth / 2, y + 6, { align: "center" });

      // Save
      doc.save(`MediAI_Slip_${appointment.id}.pdf`);
    } catch (error) {
      console.error("PDF Generation Error:", error);
      alert("Sorry, there was an error generating the PDF. Please check your browser settings or try again.");
    }
  };

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-xl shadow-2xl max-w-md w-full overflow-hidden animate-in fade-in zoom-in duration-200">
        <div className="bg-blue-600 p-6 text-white text-center relative">
          <button 
            onClick={onClose}
            className="absolute top-4 right-4 text-blue-200 hover:text-white p-1 rounded-full hover:bg-blue-700 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
          <h2 className="text-2xl font-bold">MediAI Pro Hospital</h2>
          <p className="text-blue-100 text-sm mt-1">Official Appointment Slip</p>
        </div>
        
        <div className="p-6 space-y-6">
          <div className="flex justify-between items-center border-b pb-4 border-slate-100">
            <div>
              <p className="text-xs text-slate-500 uppercase font-bold tracking-wider">Appointment ID</p>
              <p className="font-mono text-2xl font-bold text-slate-800">#{appointment.id}</p>
            </div>
            <div className="h-12 w-12 bg-blue-50 rounded-full flex items-center justify-center">
              <Calendar className="w-6 h-6 text-blue-600" />
            </div>
          </div>

          <div className="space-y-4">
            <div className="flex items-center space-x-4 p-3 bg-slate-50 rounded-lg">
              <div className="w-10 h-10 rounded-full bg-white border border-slate-200 flex items-center justify-center flex-shrink-0">
                <User className="w-5 h-5 text-slate-600" />
              </div>
              <div>
                <p className="text-xs text-slate-500">Patient</p>
                <p className="font-semibold text-slate-900">{appointment.patientName}</p>
              </div>
            </div>

            <div className="flex items-center space-x-4 p-3 bg-slate-50 rounded-lg">
              <div className="w-10 h-10 rounded-full bg-white border border-slate-200 flex items-center justify-center flex-shrink-0">
                <User className="w-5 h-5 text-blue-600" />
              </div>
              <div>
                <p className="text-xs text-slate-500">Doctor</p>
                <p className="font-semibold text-slate-900">{appointment.doctor.name}</p>
                <span className="text-xs text-blue-600 font-medium bg-blue-100 px-2 py-0.5 rounded-full">
                  {appointment.doctor.specialty}
                </span>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div className="p-3 bg-slate-50 rounded-lg">
                <p className="text-xs text-slate-500 mb-1 flex items-center gap-1"><Calendar className="w-3 h-3" /> Date</p>
                <p className="font-semibold text-slate-900">{appointment.date}</p>
              </div>
              <div className="p-3 bg-slate-50 rounded-lg">
                 <p className="text-xs text-slate-500 mb-1 flex items-center gap-1"><Clock className="w-3 h-3" /> Time</p>
                <p className="font-semibold text-slate-900">{appointment.time}</p>
              </div>
            </div>
          </div>
        </div>

        <div className="bg-slate-50 p-4 border-t flex gap-3">
          <button 
            onClick={onClose}
            className="flex-1 text-slate-600 hover:text-slate-900 font-medium text-sm py-2.5 hover:bg-slate-100 rounded-lg transition-colors"
          >
            Close
          </button>
          <button 
            onClick={handleDownload}
            type="button"
            className="flex-1 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2.5 rounded-lg font-medium text-sm flex items-center justify-center gap-2 shadow-lg shadow-blue-600/20 transition-all active:scale-95"
          >
            <Download className="w-4 h-4" />
            Download PDF
          </button>
        </div>
      </div>
    </div>
  );
};